apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    app: consumer
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: consumer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consumer-monitor
  labels:
    app: consumer
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: consumer
  endpoints:
  - port: http
