apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: simonliska/tuesday:crti-latest
        imagePullPolicy: Always
        command: ["python", "consumer.py", "output.txt"] 
        # env:
        # - name: RABBITMQ_URL
        #   value: "amqp://user:PASSWORD@my-rabbitmq.default.svc.cluster.local"
